version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb-pagination
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_pagination_data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-pagination-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8082:8081
    depends_on:
      - mongodb
    
  product-service-pg:
    image: bitnami/postgresql
    container_name: pagination-pg
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=product_username
      - POSTGRESQL_PASSWORD=product_password
      - POSTGRESQL_DATABASE=product
    volumes:
    - postgres_data_pagination:/bitnami/postgresql

volumes:
  mongodb_pagination_data:
  postgres_data_pagination: